name: Frontend Image CI

on:
  push:
    paths:
      - 'src/frontend/**'
  pull_request:
    paths:
      - 'src/frontend/**'
  workflow_dispatch:

jobs:
  build:
    environment: Dev
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Set up Docker Buildx (for multi-platform builds & caching)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

      # Build and push Docker image
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: ./src/frontend
        file: ./src/frontend/Dockerfile
        push: true
        tags: |
          thuyein97/frontend:latest
          thuyein97/frontend:${{ github.sha }}
